### ISSUE TITLE
Now.sh Deployment

### ISSUE THREAD

**Issue by SecuritySleuth** [brandiqa/simplewebrtc-messenger#2]
Hi,

When attempting to build this in Now.sh and a node-express 

for some reason the images, buttons and static content aren't working

![screenshot from 2018-12-24 16 21 07](https://user-images.githubusercontent.com/45907718/50391372-14638280-0798-11e9-9c7c-379cedd004d3.png)
t

My now.json file looks like the following:
`
{
    "version": 2,
    "name": "nodejs-express",
    "builds": [
        { "src": "server.js", "use": "@now/node-server" }
    ],
    "routes": [
        { "src": "/(.*)", "dest": "server.js" }
    ]
}`

Any chance you can help? Apologies if this seems obvious I'm not very familiar with Node

**Comment by brandiqa** [comment]
Hi,

I can look into it in January. Am currently on holiday.

Regards,
Michael

**Comment by SecuritySleuth** [comment]
After some further playing with the now.sh setup and deployment with the following config
`{
    "version": 2,
    "name": "vchat-app",
    "builds": [
        { "src": "package.json", "use": "@now/static-build", "config": {"distDir": "public"} }
    ]
}
`

It looks like some build errors in node are whats stopping the deploy as per the now logs:
`01/11 12:00 PM (36s)
running yarn for @now/static-build...
01/11 12:00 PM (36s)
yarn add v1.12.3
01/11 12:00 PM (35s)
info No lockfile found.
01/11 12:00 PM (35s)
[1/4] Resolving packages...
01/11 12:00 PM (35s)
[2/4] Fetching packages...
01/11 12:00 PM (35s)
[3/4] Linking dependencies...
01/11 12:00 PM (35s)
warning " > @now/static-build@0.4.16" has unmet peer dependency "@now/build-utils@>=0.0.1".
01/11 12:00 PM (35s)
[4/4] Building fresh packages...
01/11 12:00 PM (35s)
success Saved lockfile.
01/11 12:00 PM (35s)
success Saved 1 new dependency.
01/11 12:00 PM (35s)
info Direct dependencies
01/11 12:00 PM (35s)
└─ @now/static-build@0.4.16
01/11 12:00 PM (35s)
info All dependencies
01/11 12:00 PM (35s)
└─ @now/static-build@0.4.16
01/11 12:00 PM (35s)
Done in 0.59s.
01/11 12:00 PM (34s)
yarn cache v1.12.3
01/11 12:00 PM (34s)
warning package.json: No license field
01/11 12:00 PM (34s)
success Cleared cache.
01/11 12:00 PM (34s)
Done in 0.04s.
01/11 12:00 PM (34s)
cache name undefined
01/11 12:00 PM (34s)
workPath is /tmp/66090d33
01/11 12:00 PM (34s)
running builder.exports.build...
01/11 12:00 PM (34s)
downloading user files...
01/11 12:00 PM (34s)
downloading https://dmmcy0pwk6bqi.cloudfront.net/1aaddf05c6c8556601fb88d307978e3fdc4cc99a: 315.019ms
01/11 12:00 PM (34s)
downloading https://dmmcy0pwk6bqi.cloudfront.net/9c6eb23826d8665360813c6a62086ecc3c09d2ab: 317.983ms
downloading https://dmmcy0pwk6bqi.cloudfront.net/dca74bbbc5ff9ec1db48526bdf17d4536449720a: 321.393ms
01/11 12:00 PM (34s)
downloading https://dmmcy0pwk6bqi.cloudfront.net/6802b9b9ccb617609347c1e93745049759bd49eb: 329.346ms
01/11 12:00 PM (34s)
downloading https://dmmcy0pwk6bqi.cloudfront.net/07a731987688a2bb14e9b5fe55071b67592f74aa: 329.795ms
01/11 12:00 PM (34s)
downloading https://dmmcy0pwk6bqi.cloudfront.net/8e37b1cf68a21c3d9bed13a1ac8c77a1fc127ef1: 345.140ms
01/11 12:00 PM (34s)
downloading https://dmmcy0pwk6bqi.cloudfront.net/83445f422f09a2fafb698bc3467ddbda7eb6fe4b: 353.540ms
01/11 12:00 PM (34s)
downloading https://dmmcy0pwk6bqi.cloudfront.net/63b7714d8e695592f8edfcaff7e1f9aedf5b6e67: 353.345ms
01/11 12:00 PM (34s)
downloading https://dmmcy0pwk6bqi.cloudfront.net/3300ce92cf5a3cfb4792795a29b8a25b61c09903: 375.585ms
01/11 12:00 PM (34s)
downloading https://dmmcy0pwk6bqi.cloudfront.net/8e73f83309ad7cb6b8aa349a444b71f32d753e65: 387.712ms
01/11 12:00 PM (34s)
running user scripts...
01/11 12:00 PM (34s)
installing to /tmp/66090d33
01/11 12:00 PM (32s)
npm
01/11 12:00 PM (32s)
 
01/11 12:00 PM (32s)
WARN
01/11 12:00 PM (32s)
 
01/11 12:00 PM (32s)
notice
01/11 12:00 PM (32s)
 [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
01/11 12:00 PM (32s)
npm
01/11 12:00 PM (32s)
 WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
01/11 12:00 PM (31s)
npm 
01/11 12:00 PM (31s)
WARN notice [SECURITY] parsejson has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=parsejson&version=0.0.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
01/11 12:00 PM (29s)
added 117 packages in 3.82s
01/11 12:00 PM (29s)
npm
01/11 12:00 PM (29s)
 
01/11 12:00 PM (29s)
WARN 
01/11 12:00 PM (29s)
using --force I sure hope you know what you are doing.
01/11 12:00 PM (29s)
patching https://api-sfo1.zeit.co/v2/now/deployments/dpl_3BDXn4qfoSbBt2yZCCXxsUHd644X/builds/bld_cqojgtnw5 with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
01/11 12:00 PM (29s)
{ Error: An error running "now-build" script in "package.json"
    at Object.exports.build (/tmp/utils/build-module/node_modules/@now/static-build/index.js:29:11)
    at <anonymous> reported: true }`

**Comment by RbnBecker** [comment]
Is there any solution?

**Comment by shahnazmshariff** [comment]
Facing the same issue, is there any solution?

**Comment by brandiqa** [comment]
Deployment with now.sh has just been fixed in order to be compliant with https://zeit.co/docs/v2/advanced/platform/frequently-asked-questions#missing-build-script. Do note this project has no builder so I had to manually copy and replace scripts with CDN URL. I've also updated the README.md to indicate this project is no longer maintainable.
