### ISSUE TITLE
Peer connection disconnecting randomly

### ISSUE THREAD

**Issue by shekhriz** [brandiqa/simplewebrtc-messenger#3]
The peers are able to connect to a room fine. However, after a short period of time ( < 1 min ), user 1's remote video freezes and user 2's remote video goes black. They are unable to reconnect and the room is unusable until everyone leaves the room. This error repeats nomatter the room name or number of connections. Any ideas?

**Comment by brandiqa** [comment]
What is the **upload** bandwidth speed for user 1 and user 2?

**Comment by brandiqa** [comment]
Am closing this issue since simplewebrtc has been deprecated, hence this entire project has been deprecated. See Readme.md
