### ISSUE TITLE
Reason: CORS request did not succeed

### ISSUE THREAD

**Issue by ahasantech** [brandiqa/simplewebrtc-messenger#5]
Dear Concern, thanks for code, I used the code, but when project run browser show below error message, how i solved it's, can you suggest me.

my project create Cpanel directory folder.

GET https://sandbox.simplewebrtc.com/socket.io/?EIO=3&transport=polling&t=1586766461078-4 
![2](https://user-images.githubusercontent.com/61349388/79106266-37e28000-7d83-11ea-926d-d12b050d1089.png)
![1](https://user-images.githubusercontent.com/61349388/79106269-3add7080-7d83-11ea-8bb0-cc4cb6568890.png)
![3](https://user-images.githubusercontent.com/61349388/79106272-3c0e9d80-7d83-11ea-9972-4acea0c2f47d.png)

**Comment by brandiqa** [comment]
Hi,

Sorry for the inconvenience. Unfortunately the open source library is
broken. It has been replaced by a commercial library. The servers used for
performing webrtc connections are no longer active.

Regards,
Michael

**Comment by ahasantech** [comment]
Dear Thanks for replay, but i used all your resource, can help me how solved the issue without commercial issue. i hope you give me suggestion.

**Comment by brandiqa** [comment]
I've checked all open source libraries and none are working. I would
recommend you check out simplewebrtc.com. They have a plan that charges $5 per
GB. It's free to signup.

I haven't used them, let me know how it goes

**Comment by ahasantech** [comment]
Thanks for quick response . can you give me suggestion or make its, how i will don the projects.
my client  requirements:

- one broadcast video , more than 100 views 
- conference video chat , and admin can mute sound or camera for anyone 
- drawing board  , admin draw more than 50 watch ... also admin can active  any user to draw and inactive
- shear-screen for full desktop not only one browser page
- admin can convert from video chat only to drawing screen or shear screen    Without cut connection

**Comment by brandiqa** [comment]
I've never built such an app. I wouldn't know how to go about it. There are
already commercial applications such as Skype that provide the same
features.

Sorry, can't help you with this.

All the best

**Comment by ahasantech** [comment]
Thanks for Reply.

**Comment by anjumdar7864** [comment]
i can also use ant media server for connection ?
